### ISSUE TITLE
Github admin

### ISSUE THREAD

**Issue by bobbysebolao** [facn6/EatWrite#14]
Hi team, here are a few comments from me:

- Please can you update your issues with priority 1 labels? These are the most urgent issues that you should currently be working on

- Why are you not using Github projects to track to do/in progress/completed user stories? What method are you using instead? It's best to use Github for all your project management stuff (Github should be your single source of truth)

- I will code review your project this evening and leave you some constructive issues

**Comment by kira-abl** [comment]
@bobbysebolao I think this issue can be closed now. What do you say?
